### ISSUE TITLE
Set up test instances for ES nested search evaluation.

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/distribution-component#6]
DoD:

Two instances of Elastic search

- [x] elasticsearch v 1.3.4 + siren plugin
- [x] latest elasticseach + custom config

Containarize instances with the data.

Testing:
Peer Review

**Comment by blankdots** [comment]
Latest elastic search image: `elasticsearch:5.1.2` from: https://hub.docker.com/_/elasticsearch/

**Comment by blankdots** [comment]
@jkesanie @joasilva which ports should we use for the new Elasticsearch (the one with version 5.1.2)? I am having trouble accessing the new elasticsearch (5.1.2) for BDD testing related to issues:
* https://github.com/ATTX-project/graph-component/issues/8
* https://github.com/ATTX-project/graph-component/issues/10

**Comment by joasilva** [comment]
Image created and pushed to our private registry as "attx-dev:5000/attx-es5:latest". The exposed ports are 9210 and 9310

Dockerfile, configs, build.gradle, entrypoint script, etc. pushed to https://github.com/ATTX-project/platform-deployment/tree/feature-attx-es5/attx-es5.

build.gradle field for generating docker-compose.yml updated @ https://github.com/ATTX-project/platform-deployment/blob/feature-attx-es5/dcompose/build.gradle
